USER_NAME = funkypenguin18

qq


export USER_NAME

build: post comment ui prometheus 
push: push_comment push_post push_ui push_prometheus 

post: 
	cd src/post-py && bash docker_build.sh
comment: 
	cd src/comment && bash docker_build.sh
ui: 
	cd src/ui && bash docker_build.sh

prometheus:
	cd monitoring/prometheus && docker build -t ${USER_NAME}/prometheus .
alertmanager:
	cd monitoring/alertmanager && docker build -t ${USER_NAME}/alertmanager .

push_post:
	docker push ${USER_NAME}/post
push_comment:
	docker push ${USER_NAME}/comment
push_ui:
	docker push ${USER_NAME}/ui
push_prometheus:
	docker push ${USER_NAME}/prometheus
push_cloudprober:
	docker push ${USER_NAME}/cloudprober
push_alertmanager:
	docker push ${USER_NAME}/alertmanager
